[build]
  functions = "netlify/functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["node-fetch"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/proxy"
  status = 200
  force = true

[functions.proxy]
  maxDuration = 30